apiVersion: v1
kind: Service
metadata:
  name: express-server
  lables:
    app: express-server
spec:
  clusterIP: none
  selector:
    app: express-server
  ports:
    - port: 5050
      targetPort: 5050