apiVersion: v1
kind: Service
metadata:
  name: express-server
  labels:
    app: express-server
spec:
  type: NodePort
  selector:
    app: express-server
  ports:
    - port: 5050
      nodePort: 30002